site_name: Moodle-Kurse
site_url: https://ThomasBeckmann.github.io/test/
nav:
    - Einleitung zum LF7: 'index.md'


theme: 
    name: readthedocs
    locale: de
    include_homepage_in_sidebar: ture
    
    

