site_name: Moodle Kurse

theme:
  name: material
  language: de
  font: false

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences

plugins:
  - include-markdown

use_directory_urls: false

site_dir: 'site'
