site_name: Moodle-Kurse
repo_url: https://github.com/ThomasBeckmann/test/

plugins:
  - include-markdown

theme:
  name: material
  palette:
    primary: orange
    accent: red
   
repo_url: https://github.com/ThomasBeckman/test

site_url: https://ThomasBeckmann.io/test/

nav:
    - Einleitung zum LF2: 'index.md'
    - Kapitel 00 - Organisatorisches: 'kapitel_00.md'
    - Kapitel 01 - Propädeutikum: 'kapitel_01.md'
    - Kapitel 02 - IT-Systeme auswählen: 'kapitel_02.md'
    - Kapitel 03 - Netzwerkspeicher dimensionieren: 'kapitel_03.md'
    - Kapitel 04 - IT-Systeme in Betrieb nehmen: 'kapitel_04.md'
    - Kapitel 05 - Sensoren auslesen: 'kapitel_05.md'
    - Kapitel 06 - Aktoren ansteuern: 'kapitel_06.md'
