site_name: Moodle-Kurse
repo_url: https://github.com/ThomasBeckmann/test/

plugins:
  - include-markdown
   
repo_url: https://github.com/ThomasBeckman/test

site_url: https://ThomasBeckmann.io/test/

nav:
    - TesNav: 'index.md'
