site_name: Moodle-Kurse
repo_url: https://github.com/ThomasBeckmann/test/

plugins:
  - include-markdown

theme:
  name: material
  palette:
    primary: orange
    accent: red
   
repo_url: https://github.com/ThomasBeckman/test

site_url: https://ThomasBeckmann.io/test/

site_nav:
    - TesNav: 'index.md'
